# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  nginxBuildDirectory: 'nginx-fpm/0.4/'
  nginxImageName: 'nginx-fpm'
  wpBuildDirectory: 'wordpress-alpine-php/0.61/'
  wordpressImageName: 'wordpress-alpine-php'
 
steps:
- task: Docker@1
  displayName: 'Login to Azure Container Registry'
  inputs:
    command: login
    azureSubscriptionEndpoint: 'Azure CXP FT Internal Subscription JOSCOT (6956ed15-2e18-4b8e-9db7-6a61647dedfb)'
    azureContainerRegistry: joscot.azurecr.io

- task: Docker@1
  displayName: 'Build nginx image'
  inputs:
    imageName: 'joscot.azurecr.io/$(nginxImageName):$(build.buildId)'
    dockerFile: '$(nginxBuildDirectory)/Dockerfile'
    useDefaultContext: true
    includeLatestTag: true
 
- task: Docker@1
  displayName: 'Push nginx image to Azure Container Registry'
  inputs:
    command: 'Push an Image'
    imageName: 'joscot.azurecr.io/$(nginxImageName)'

- task: Docker@1
  displayName: 'Build wordpress image'
  inputs:
    imageName: 'joscot.azurecr.io/$(wordpressImageName):$(build.buildId)'
    dockerFile: '$(wpBuildDirectory)/Dockerfile'
    useDefaultContext: true
    includeLatestTag: true
 
- task: Docker@1
  displayName: 'Push wordpress image to Azure Container Registry'
  inputs:
    command: 'Push an Image'
    imageName: 'joscot.azurecr.io/$(wordpressImageName)'

